services:
  backend:
    container_name: techstore-backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: "1"

  frontend:
    container_name: techstore-frontend
    build:
      context: ./frontend
    ports:
      - "5175:5175"
    environment:
      VITE_API_URL: http://localhost:8000/api
    depends_on:
      - backend
